# version: "3.11"
# my lite llm file
services:
  litellm:
    build:
        context: .
        args:
          target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
        LITELLM_MASTER_KEY: "sk-1234"
        DATABASE_URL: "postgresql://root:password@db:5432/postgres"
        STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
        LITELLM_LICENSE: "sk-1234"
 
  db:
    image: postgres:16
    ports:
      - "5432:5432" # Expose the PostgreSQL port
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

